#version: '3.8'
services:

  mysql:
    build:
        context: .
        dockerfile: Dockerfile.mysql
    ports:
      - "3307:3307"
    env_file: ".env.docker"
    healthcheck:
       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
       timeout: 2s
       retries: 10
    networks:
      - shared-network

  web-app:
    depends_on:
       mysql:
         condition: service_healthy
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file: ".env.docker"
      
    networks:
      - shared-network
 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # RabbitMQ management plugin port
    env_file: ".env.docker"
    volumes:
      - ./dev-ops/rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf  
       - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - shared-network       

volumes:
  rabbitmq_data:
    driver: local  
      
networks:
  shared-network:
    driver: bridge 