#version: '3.8'
services:
  web-app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file: ".env.docker"
      
    networks:
      - shared-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # RabbitMQ management plugin port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./RabbitMQ/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf  
       - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - shared-network       
volumes:
  rabbitmq_data:
    driver: local    
networks:
  shared-network:
    driver: bridge 